# Generated by Django 2.1.2 on 2018-12-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181209_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[
	            ('TV', 'travel'),
	            ('RX', 'relax'),
	            ('MC', 'music'),
	            ('EC', 'education')
            ], default='RX', max_length=20),
        ),
    ]
